### ISSUE TITLE
 problems with overlap of tables.

### ISSUE THREAD

**Issue by damiansire** [damiansire/Plan_Matematica#4]
When courses are added, if they overlap with the next table, let the entire row below, go down.
The entire row of tables below must go down.

**Comment by nicoleCamoro** [comment]
can I take this?

**Comment by damiansire** [comment]
Soumya44 is cleaning the code, if you wait for it to end, you can do it :)

**Comment by BrNaka** [comment]
Is this problem that you are facing?

![screenshot from 2018-10-02 01-11-31](https://user-images.githubusercontent.com/31754622/46328880-470a3e80-c5e0-11e8-9f5f-a41f85c47d4b.png)

**Comment by damiansire** [comment]
> can I take this?

Idon't know how assign it, but you can take it!

**Comment by damiansire** [comment]
> Using CSS-grid would be a great solution.
Thanks you BrNaka!! I'll try to do it
